### ISSUE TITLE
Inappropriate README content.

### ISSUE THREAD

**Issue by vetri-selvam** [Pranavh002/Guess-the-number-project-using-react#1]
Hi @Pranavh002 . I have seen the README of your repo and it's the basic in-build content that you get for every newly created react app. 

Instead, you could use the below content. 

# Guess The Number

Welcome to the **Guess The Number** game! This is a simple React application where the user tries to guess a randomly generated number within a specified range.

## Table of Contents

- [Installation](#installation)
- [Usage](#usage)
- [Features](#features)

## Installation

To get started with the project, clone the repository and install the dependencies:

```bash
git clone https://github.com/yourusername/guess-the-number.git
cd guess-the-number
npm install
```

## Usage

To run the application locally, use the following command:

```bash
npm start
```

This will start the development server and you can view the application in your browser at `http://localhost:3000`.

## Features

- **Random Number Generation**: The app generates a random number within a specified range.
- **User Input**: Users can input their guesses and receive feedback.
- **Hints**: The app provides hints whether the guess is too high or too low.
- **Reset Functionality**: Users can reset the game to start over.

**Comment by Pranavh002** [comment]
Thank You @vetri-selvam! 
I have made the changes to the README file as per your suggestion.  Appreciate your feedback!
Feel free to check it out and let me know if you have any further feedback
